src/server/README.md, src/server/app.py, src/server/requirements.txt
Basic Flask app structure with directories for routes and models, and a minimal `requirements.txt` file. 
Two things in particular that may be worth discussing:
- I've included CORS, I don't think that this is necessary for the desktop cient but is good practice and I believe necessary if we decide to do a web client. 
- I suggest using blueprints for routes to seperate login and authenitcation logic. There's an example of registering blueprints in `app.py` but this isn't necessary.
=> create Flask app

src/desktop-client/client-404/mainwindow.cpp, src/desktop-client/client-404/uploadfilepage.cpp
- Using the encryption helper class generateKey, generateNonce and encrypt methods to encrypt file data and authenticate metadata
- wrapped in a try catch block with a ui warning on error to notify the user that something went wrong
- Clear the keys after encryption for extra safety
closes https://github.com/ElliceNels/blocksblocks/issues/19
=> Encrypt the uploaded files

src/server/utils/auth.py, src/server/utils/file.py, src/server/utils/jwt.py, src/server/utils/permission.py
Use context manager (with keyword) for database access ensuring:
- Sessions always close
=> [Fix] Change db session use to context manager style

src/desktop-client/client-404/fileitemwidget.cpp, src/desktop-client/client-404/loginpage.cpp, src/desktop-client/client-404/loginsessionmanager.cpp, src/desktop-client/client-404/mainmenu.cpp, src/desktop-client/client-404/mainwindow.cpp, src/desktop-client/client-404/registerpage.cpp, src/desktop-client/client-404/titlepage.cpp, src/desktop-client/client-404/uploadfilepage.cpp, src/desktop-client/client-404/verifypage.cpp, src/desktop-client/client-404/viewfilespage.cpp
In the project spec, it says this is required : "this Pointer: Illustrate the use of the this pointer to refer to the current object within
a class's member functions. "
will be merged in after https://github.com/ElliceNels/fourohfour/pull/38
=> Use of this->

src/server/routes/authentication_routes.py
Just a lil one bc we were still parsing the request header to get the jwt token. Changed to use the same utility function everywhere
=> use get_current_token wherever possible

tests/server/utils/test_auth.py, tests/server/utils/test_file.py
Quick PR to use a lightweight flask app for testing instead of actual app from app.py
=> [Fix] Use lightweight flask app for testing

src/desktop-client/client-404/constants.h, src/desktop-client/client-404/mainmenu.ui, src/desktop-client/client-404/uploadfilepage.ui, src/desktop-client/client-404/verifypage.ui
Pages improved
view files will be in another pr
=> More ui page improvements

src/server/test_db_connection.py, tests/server/utils/test_db_connection.py
This builds on top of https://github.com/ElliceNels/fourohfour/pull/36
=> Db testing

.gitignore, src/server/utils/auth.py, tests/server/utils/test_auth.py
small things
1. Everytime I run the C++ side a load of files in the `build-client-404-Desktop_Qt_6_7_0_MinGW_64_bit-Debug` directory were created. Added a line to gitignore to fix (or maybe im doing something wrong 😳)
2. Our login route was accepting a string for the public key, but when putting it into the database we were assuming it was in bytes. Added this conversion and updated tests
=> Small bugs (fleas)

src/server/models/tables.py, src/server/utils/auth.py, tests/server/utils/test_auth.py, tests/server/utils/test_db_connection.py
SOMEONE added a conversion from base64 encoded strings to bytes very recently and never thought that there was no reason to just use base64 strings throughout. 
Someone was me
IMPORTANT this will require a database migration to use. you can drop tables and recreate or wait and ill make a migrations script soon
=> byebyebytes

src/server/routes/authentication_routes.py, src/server/utils/auth.py, src/server/utils/jwt.py, tests/server/utils/test_auth.py, tests/server/utils/test_jwt.py
Last UTIL TEST AAAAAA now i can move to APIs
=> Jwt unit testing

src/server/utils/auth.py, tests/server/utils/test_auth.py
Error with thw way this function was being called
=> [Fix] Remove token parameter from get_current_token

src/server/routes/authentication_routes.py, src/server/routes/file_routes.py, src/server/utils/auth.py
- Add seperate catches to list_files for easier debugging
=> [FIx] Return User_id from get_current_user but hide from public route

src/desktop-client/client-404/constants.h, src/desktop-client/client-404/ui/uploadfilepage.cpp, src/desktop-client/client-404/ui/uploadfilepage.h, src/desktop-client/client-404/utils/request_utils.cpp, src/desktop-client/client-404/utils/request_utils.h
- This will be the first of a set of prs to upload files to the db
- Atm, you can only upload a file once and will receive a blocking warning when you try to upload the same file again
- Next Pr will be to handle the overwrite or rename
The copilot UUID comment make sense but the UUID and success/error message will be sorted on the next PR
=> [File Upload] Upload unique files

src/web-client/signup.py
Small fix and BLANK Files
Imma take this nice and slow and organised n stuff WOOOOOOO
=> Web files heh

src/desktop-client/client-404/ui/uploadfilepage.cpp
=> Save only the filename

src/desktop-client/client-404/constants.h, src/desktop-client/client-404/resource.qrc, src/desktop-client/client-404/ui/fileitemwidget.cpp, src/desktop-client/client-404/ui/fileitemwidget.h, src/desktop-client/client-404/ui/mainmenu.cpp, src/desktop-client/client-404/ui/mainmenu.h, src/desktop-client/client-404/ui/mainwindow.cpp, src/desktop-client/client-404/ui/mainwindow.h, src/desktop-client/client-404/ui/viewfilespage.cpp, src/desktop-client/client-404/ui/viewfilespage.h
PROOF (for those who don't run it 😞 )
https://github.com/user-attachments/assets/5685567e-96ed-4c88-afed-b300a8ea5800
=> [File Upload] View functionality

src/server/routes/file_routes.py, src/server/utils/file.py, tests/server/routes/test_file_routes.py, tests/server/utils/test_file.py
So that a client can display the username of the person who has shared files with you
=> return owner username for shared files

src/desktop-client/client-404/utils/friend_storage_utils.cpp, src/desktop-client/client-404/utils/friend_storage_utils.h
=> [Diffie Hellman] Get the users friend list (except for themselves)

src/desktop-client/client-404/utils/file_sharing_utils.cpp, src/desktop-client/client-404/utils/file_sharing_utils.h
method to generate ephemeral key pair but no storage for forward secrecy
=> [Diffie Hellman] Generate emphemeral key pair

src/server/routes/authentication_routes.py, src/server/utils/auth.py, tests/server/routes/test_authentication_routes.py, tests/server/utils/test_auth.py
Previously had no mechanism to get a spk and signature
=> Retrieve key bundle

src/web-client/app.py, src/web-client/config.json, src/web-client/static/style.css, src/web-client/templates/viewfiles.html, src/web-client/utils/view_files.py
Some small fixes to get the app running and view files working
Hopefully after ellices merges this will be rebased and go straight into main, but review would be welcome now so we cna move faster
0.0.0.0 change is bc it was having some trouble connecting to a socket or someting
=> File view fix

src/server/routes/authentication_routes.py, src/server/routes/permission_routes.py, src/server/utils/auth.py, tests/server/routes/test_authentication_routes.py, tests/server/routes/test_permission_routes.py, tests/server/utils/test_auth.py, tests/server/utils/test_file.py
login doesnt get blocked if spk is too old or not enought otpks, just sents a flag
and some random tests that were failing
=> Old spk login fix

src/server/routes/authentication_routes.py, tests/server/routes/test_authentication_routes.py, tests/server/routes/test_file_routes.py, tests/server/routes/test_permission_routes.py, tests/server/utils/test_file.py
Should fix base 64 encoding
Some permsison tests are failing but i fixd them already in another pending pr
Will redeploy once merged
=> should fix salt error

src/desktop-client/README.md, src/desktop-client/client-404/constants.h, src/desktop-client/client-404/ui/fileitemwidget.cpp, src/desktop-client/client-404/ui/loginpage.cpp, src/desktop-client/client-404/utils/request_utils.cpp, src/desktop-client/client-404/utils/request_utils.h
read me updated as well to include the instructions on how to add the cert
=> [Connect to Server] connect to server changes + readme instructions
